"""Remove user_type field and update status values

Revision ID: 6bebc4c56f23
Revises: 98d73146cb84
Create Date: 2025-06-01 21:19:13.646541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bebc4c56f23'
down_revision = '98d73146cb84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
