"""empty message

Revision ID: d0f1dddb6a79
Revises: 470d0415c00e
Create Date: 2025-05-31 16:04:53.293390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f1dddb6a79'
down_revision = '470d0415c00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcribed_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_calls', schema=None) as batch_op:
        batch_op.drop_column('transcribed_text')

    # ### end Alembic commands ###
